/* GENERATED by tools/measure-car-art.mjs — do not hand-edit.
   Re-run that tool after adding or replacing any car art.

   Each entry is one photo's painted extent, as percentages of its own
   canvas: `nose`/`tail` are the front (right) and rear (left) edges of
   the opaque pixels, and `fTop`/`fBot` (`rTop`/`rBot`) are the vertical
   span of the car within the outer 12% at that end — i.e. how wide the
   car actually is where its headlights (taillights) sit.

   js/art.js anchors the hero light overlay to these instead of to one set
   of constants tuned to classic.webp. See that file's photoHeroExtra. */
export const CAR_ART_GEOMETRY = {
  'assets/cars/classic.webp': { nose: 96.6, tail: 3.1, fTop: 10, fBot: 90.8, rTop: 9.8, rBot: 91.3 },
  'assets/cars/hero-airtail-blue.webp': { nose: 94, tail: 6, fTop: 9.3, fBot: 90, rTop: 7.8, rBot: 91.8 },
  'assets/cars/hero-airtail-pink.webp': { nose: 94, tail: 5.9, fTop: 9.3, fBot: 90, rTop: 8, rBot: 91.8 },
  'assets/cars/hero-airtail-purple-yellow.webp': { nose: 94.1, tail: 5.9, fTop: 8.8, fBot: 90.3, rTop: 7.8, rBot: 91.8 },
  'assets/cars/hero-airtail-red.webp': { nose: 94, tail: 5.9, fTop: 9, fBot: 90, rTop: 8, rBot: 91.8 },
  'assets/cars/hero-airtail-stripe.webp': { nose: 94, tail: 5.9, fTop: 9, fBot: 90, rTop: 8, rBot: 91.8 },
  'assets/cars/hero-canopy-green.webp': { nose: 98.4, tail: 1.5, fTop: 12.3, fBot: 87.8, rTop: 7, rBot: 92.8 },
  'assets/cars/hero-classic-blue-stripe.webp': { nose: 98.4, tail: 1.5, fTop: 8.8, fBot: 90.3, rTop: 11.5, rBot: 88.8 },
  'assets/cars/hero-classic-cream.webp': { nose: 98.4, tail: 1.5, fTop: 13.3, fBot: 87.3, rTop: 13.3, rBot: 87.5 },
  'assets/cars/hero-classic-white-green.webp': { nose: 98.4, tail: 1.5, fTop: 12, fBot: 86.5, rTop: 15.8, rBot: 84 },
  'assets/cars/hero-convertible-brown.webp': { nose: 98.4, tail: 1.5, fTop: 15.5, fBot: 85.3, rTop: 14, rBot: 84.5 },
  'assets/cars/hero-fluro-cyan.webp': { nose: 98.4, tail: 1.5, fTop: 13.3, fBot: 86.3, rTop: 14.5, rBot: 85 },
  'assets/cars/hero-fluro-green.webp': { nose: 98.4, tail: 1.5, fTop: 13.5, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-fluro-orange.webp': { nose: 98.4, tail: 1.5, fTop: 13.5, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-fluro-pink.webp': { nose: 98.4, tail: 1.5, fTop: 13.5, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-fluro-yellow.webp': { nose: 98.4, tail: 1.5, fTop: 13.5, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-muscle-grey-stripe.webp': { nose: 98.4, tail: 1.5, fTop: 13.3, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-muscle-sage.webp': { nose: 98.4, tail: 1.5, fTop: 13.5, fBot: 86.3, rTop: 14.8, rBot: 85 },
  'assets/cars/hero-muscle.webp': { nose: 98.5, tail: 1.4, fTop: 15, fBot: 85.3, rTop: 15.8, rBot: 84 },
  'assets/cars/hero-red-exotic.webp': { nose: 98.4, tail: 1.5, fTop: 11, fBot: 88.5, rTop: 11.8, rBot: 88.8 },
  'assets/cars/hero-sedan-bronze.webp': { nose: 98.4, tail: 1.5, fTop: 15.8, fBot: 85.5, rTop: 16, rBot: 85.5 },
  'assets/cars/hero-sedan-green.webp': { nose: 98.4, tail: 1.5, fTop: 15.8, fBot: 85.5, rTop: 16, rBot: 85.5 },
  'assets/cars/hero-sports-cyan.webp': { nose: 98.4, tail: 1.5, fTop: 13.3, fBot: 86, rTop: 12.3, rBot: 87.8 },
  'assets/cars/hero-spyder-blue.webp': { nose: 98.4, tail: 1.5, fTop: 11.8, fBot: 88.3, rTop: 11.5, rBot: 88.5 },
  'assets/cars/library-sedans-1785067674835-12-orange-coupe.webp': { nose: 98.4, tail: 1.5, fTop: 13, fBot: 86.8, rTop: 13, rBot: 87 },
  'assets/cars/library-sedans-1785067674835-13-red-hatch.webp': { nose: 97.9, tail: 2, fTop: 2.3, fBot: 98, rTop: 2, rBot: 98 },
  'assets/cars/library-sedans-1785067674835-14-green-hatch.webp': { nose: 98.4, tail: 1.5, fTop: 3, fBot: 97.3, rTop: 3, rBot: 97.3 },
  'assets/cars/library-sedans-1785067674835-15-green-coupe.webp': { nose: 98.4, tail: 1.5, fTop: 12.8, fBot: 87.8, rTop: 19.3, rBot: 81 },
  'assets/cars/library-sedans-1785067674835-5-rust-weathered.webp': { nose: 98.4, tail: 1.5, fTop: 15.8, fBot: 85.8, rTop: 16, rBot: 85.5 },
  'assets/cars/library-sedans-1785067674835-6-police.webp': { nose: 98.4, tail: 1.5, fTop: 15.8, fBot: 85.8, rTop: 16, rBot: 85.5 },
  'assets/cars/library-sedans-1785067674835-7-orange-suv.webp': { nose: 98.4, tail: 1.5, fTop: 7.5, fBot: 92.3, rTop: 9, rBot: 89.5 },
  'assets/cars/traffic-sedan-13.webp': { nose: 98.3, tail: 1.6, fTop: 16.5, fBot: 83.5, rTop: 15.8, rBot: 84 },
  'assets/cars/traffic-sedan-25.webp': { nose: 98.4, tail: 1.5, fTop: 14.2, fBot: 83.8, rTop: 14, rBot: 84 },
  'assets/cars/traffic-sedan-28.webp': { nose: 98.4, tail: 1.5, fTop: 14.2, fBot: 83.8, rTop: 14, rBot: 84 },
  'assets/cars/traffic-sedan-6.webp': { nose: 98.3, tail: 1.6, fTop: 9.8, fBot: 89.5, rTop: 9, rBot: 90.3 },
  'assets/cars/traffic-sedan-7.webp': { nose: 98.3, tail: 1.6, fTop: 13, fBot: 86.8, rTop: 13.3, rBot: 85.8 },
  'assets/cars/traffic-sedan-new-lightblue.webp': { nose: 98.4, tail: 1.5, fTop: 18.3, fBot: 82.5, rTop: 17.5, rBot: 83 },
  'assets/cars/traffic-truck-1.webp': { nose: 98.4, tail: 1.5, fTop: 7, fBot: 89.5, rTop: 1.5, rBot: 98.3 },
  'assets/cars/traffic-truck-2.webp': { nose: 98.4, tail: 1.5, fTop: 6.5, fBot: 92.8, rTop: 1.5, rBot: 97.8 },
  'assets/cars/traffic-truck-3.webp': { nose: 98.4, tail: 1.5, fTop: 2.3, fBot: 97.5, rTop: 10.3, rBot: 90 },
  'assets/cars/traffic-truck-4.webp': { nose: 98.4, tail: 1.6, fTop: 10.8, fBot: 92.3, rTop: 16.5, rBot: 85 },
  'assets/cars/traffic-truck-5.webp': { nose: 98.4, tail: 1.5, fTop: 1.5, fBot: 98.3, rTop: 9.5, rBot: 90.8 },
  'assets/cars/traffic-truck-6.webp': { nose: 98.4, tail: 1.6, fTop: 36.8, fBot: 64.3, rTop: 4.8, rBot: 96 },
  'assets/cars/traffic-truck-7.webp': { nose: 98.4, tail: 1.5, fTop: 43, fBot: 56.8, rTop: 4.8, rBot: 94.8 },
  'assets/cars/traffic-truck-8.webp': { nose: 98.3, tail: 1.6, fTop: 21.5, fBot: 77, rTop: 5.3, rBot: 93.8 },
  'assets/cars/traffic-truck-new-rusty.webp': { nose: 98.4, tail: 1.5, fTop: 5.5, fBot: 94.3, rTop: 6, rBot: 95 },
  'assets/cars/traffic-truck-new-white.webp': { nose: 95.6, tail: 4.3, fTop: 6.8, fBot: 93.3, rTop: 7.8, rBot: 92 },
  'assets/cars/traffic-truck-new.webp': { nose: 98.4, tail: 1.5, fTop: 10.3, fBot: 88, rTop: 10.3, rBot: 88 },
  'assets/cars/truck-flatbed-green.webp': { nose: 98.4, tail: 1.5, fTop: 3, fBot: 97, rTop: 12.3, rBot: 88.8 },
  'assets/cars/truck-mixer-cream.webp': { nose: 96.2, tail: 3.9, fTop: 8.8, fBot: 91.3, rTop: 1.5, rBot: 98.3 },
  'assets/cars/truck-offroad-pickup-grey.webp': { nose: 90.6, tail: 9.3, fTop: 4.5, fBot: 95, rTop: 4.3, rBot: 95 },
  'assets/cars/truck-panel-orange.webp': { nose: 98.4, tail: 1.5, fTop: 2, fBot: 98, rTop: 3.3, rBot: 93.5 },
  'assets/cars/truck-rollback-orange.webp': { nose: 93.2, tail: 6.8, fTop: 6.5, fBot: 96.8, rTop: 1.5, rBot: 98.3 },
  'assets/cars/truck-tanker-steel.webp': { nose: 98.4, tail: 1.5, fTop: 19, fBot: 83.3, rTop: 14.8, rBot: 85 },
};
