#!/usr/bin/env node
/* 200 -> 500 campaign expansion (docs/LEVELS-500-PLAN.md), per explicit
   direction: reorder ALL existing levels so difficulty climbs smoothly,
   with a slower incline, all the way to level 500 across 10 chapters of
   50 (was 4 chapters of 50).

   Combines four sources into one pool, sorts by difficulty-model score
   `d` (not just par — d already folds in branching/uniqueness/
   counterintuitive-move factors, see js/solver.js rate()), and slices
   into 10 contiguous chapters of 50. Because the WHOLE pool is sorted
   once and cut into contiguous chunks, chapter boundaries are
   monotonically increasing by construction — no separate boundary-slack
   logic needed (that machinery in the original generate-levels.mjs
   existed to cope with per-band supply scarcity; here there's comfortable
   surplus across the whole range, confirmed by an actual supply audit
   before this ran, not assumed).

   Sources:
     1. The existing 200 shipped levels (js/levels.data.js) — same
        boards, just repositioned. Their `key` is exported to
        js/legacy-campaign-keys-v1.js in their OLD order BEFORE this
        overwrites anything, so js/game.js can migrate save.stars/best/
        jobClears from old index -> board key -> new index and no
        player's earned progress silently vanishes into the reorder.
     2. .genwork/bridge-pool.json — rehardening the existing campaign's
        own strongest boards further (tools/gen-500-bridge.mjs): far more
        efficient than sampling from scratch, and lands data exactly in
        the d20-44 range that was otherwise thin.
     3. .genwork/native-500-pool.json (m>=10 only — the sample-phase
        floor produced many trivial sub-par-10 boards not worth keeping)
        — supplemental fresh native generation, wallMax 6.
     4. .genwork/fogleman-reserve-scored.json — the 821 unclaimed
        Fogleman-database boards (tools/score-fogleman-reserve.mjs),
        already re-verified against our own solver and scored.

   Usage: node tools/extend-to-500.mjs [--dry-run] */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { solve, levelKey, EXIT_ROW } from '../js/solver.js';

const DRY_RUN = process.argv.includes('--dry-run');
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LEVELS_PATH = join(ROOT, 'js', 'levels.data.js');
const LEGACY_KEYS_PATH = join(ROOT, 'js', 'legacy-campaign-keys-v1.js');

const TOTAL = 500;
const PER_CHAPTER = 50;
const NUM_CHAPTERS = TOTAL / PER_CHAPTER;
const INTRO_PARS = [6, 8, 8];

// Chapter theme + mode-scaling taper (LEVELS-500-PLAN.md §2): heistSlack
// tapers 28%->15%, pursuitThink (bonus seconds on top of 1s/optimal-move)
// grows from 0 once boards get hard enough that flat 1s/move leaves no
// think time at all.
const CHAPTER_META = [
  { name: 'Night Shift',    accent: '#ffb454', heistSlack: 0.28, pursuitThink: 0 },
  { name: 'Neon District',  accent: '#4fd2f0', heistSlack: 0.26, pursuitThink: 0 },
  { name: 'Harbor Freight', accent: '#37c8ab', heistSlack: 0.25, pursuitThink: 0 },
  { name: 'Gridlock',       accent: '#f26fb1', heistSlack: 0.24, pursuitThink: 1 },
  { name: 'Overpass',       accent: '#e0a83a', heistSlack: 0.22, pursuitThink: 2 },
  { name: 'Freight Yard',   accent: '#c9782e', heistSlack: 0.21, pursuitThink: 3 },
  { name: 'Customs',        accent: '#8f6fd0', heistSlack: 0.20, pursuitThink: 4 },
  { name: 'Rush Hour',      accent: '#d4471f', heistSlack: 0.19, pursuitThink: 6 },
  { name: 'The Syndicate',  accent: '#5c5248', heistSlack: 0.17, pursuitThink: 8 },
  { name: 'Vault Row',      accent: '#8f0e1f', heistSlack: 0.15, pursuitThink: 10 },
];

function loadJsonIfExists(path, fallback = []){
  return existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback;
}

console.log('Loading sources…');
const existingMod = await import(LEVELS_PATH + '?t=' + Date.now());
const existingLevels = existingMod.LEVELS;
console.log(`  existing campaign: ${existingLevels.length} levels`);

// 1. Export legacy key order BEFORE anything else touches levels.data.js.
const legacyKeys = existingLevels.map(lv => {
  const pieces = lv.p.map(a => ({ r: a[0], c: a[1], len: a[2], dir: a[3] }));
  return levelKey(pieces, lv.w || []);
});
if(!DRY_RUN){
  writeFileSync(LEGACY_KEYS_PATH, `/* AUTO-GENERATED by tools/extend-to-500.mjs — do not edit by hand.
   The 200 pre-expansion campaign levels' board keys, in their OLD
   (pre-reorder) index order. js/game.js's boot migration uses this to
   move a save's stars/best/jobClears from an old array index to
   whatever new index that same board landed on after the 200->500
   reorder — see migrateCampaignProgress(). Never regenerate this file:
   it's a one-time snapshot of history, not derived from current data. */
export const LEGACY_CAMPAIGN_KEYS_V1 = ${JSON.stringify(legacyKeys)};
`);
  console.log(`  wrote ${LEGACY_KEYS_PATH} (${legacyKeys.length} keys)`);
}

const bridgePool = loadJsonIfExists(join(ROOT, '.genwork', 'bridge-pool.json'));
const nativePool = loadJsonIfExists(join(ROOT, '.genwork', 'native-500-pool.json')).filter(l => l.m >= 10);

// The raw Fogleman reserve is heavily front-loaded (221 boards at par 38
// alone, out of 821 total) — since it's ~70% of all candidates, a
// proportional/representative sample downstream would still pull ~70%
// of ANY 500-board selection from this one narrow d41-56 cluster,
// squeezing 6+ chapters' worth of content into a nearly indistinguishable
// score band (this happened, on the first attempt at this script — the
// fix is here, at the source, not in how the sample is drawn later).
// Capping how many boards survive per PAR VALUE — spread across each
// par's own score range, not just its first N in the file — flattens
// that density before it ever reaches the combine/sample step.
const PER_PAR_CAP = 20;
// Fogleman's exhaustive enumeration doesn't enforce our stricter "never a
// wall in the exit row" rule (his solver just avoids that cell in the
// actual solution path; ours treats any exit-row obstruction as
// categorically invalid regardless of whether that particular puzzle's
// solution happens to need it) — 14 of the 821 reserve boards have one,
// filtered out here before they can reach the campaign.
const foglemanRaw = loadJsonIfExists(join(ROOT, '.genwork', 'fogleman-reserve-scored.json'))
  .filter(lv => !(lv.w || []).some(w => w[0] === EXIT_ROW));
const byPar = new Map();
foglemanRaw.forEach(lv => { (byPar.get(lv.m) ?? byPar.set(lv.m, []).get(lv.m)).push(lv); });
const fogleman = [];
byPar.forEach(list => {
  list.sort((a, b) => a.d - b.d);
  if(list.length <= PER_PAR_CAP){ fogleman.push(...list); return; }
  for(let i = 0; i < PER_PAR_CAP; i++) fogleman.push(list[Math.floor(i / (PER_PAR_CAP - 1) * (list.length - 1))]);
});
console.log(`  bridge pool: ${bridgePool.length}, native pool (m>=10): ${nativePool.length}, fogleman reserve: ${fogleman.length} (capped from ${foglemanRaw.length})`);

// 2. Combine + dedupe by key. Existing levels go first so a key collision
// (shouldn't happen, but just in case) always keeps the shipped board —
// preserves h/g fields the freshly-generated sources never carry.
const seen = new Map();
existingLevels.forEach(lv => {
  const pieces = lv.p.map(a => ({ r: a[0], c: a[1], len: a[2], dir: a[3] }));
  const key = levelKey(pieces, lv.w || []);
  seen.set(key, { m: lv.m, d: lv.d, p: lv.p, w: lv.w, h: lv.h, key });
});
// Never trust a source's stored `.key` — tools/gen-500-bridge.mjs seeds
// harden() with a placeholder `key: 'seed:N'`, and when a given seed's
// hill-climb accepts zero mutations across its whole step budget (a real,
// fairly common outcome), harden() returns that seed object essentially
// unchanged, placeholder key and all. Two such placeholder-keyed entries
// that happen to describe the same underlying board as a properly-keyed
// entry elsewhere then both survive this dedup (their key STRINGS don't
// match, even though the board does) — recomputing canonically here,
// from the actual pieces+walls every time, closes that gap regardless of
// which source produced the entry or whether its own key is trustworthy.
[...bridgePool, ...nativePool, ...fogleman].forEach(lv => {
  const pieces = lv.p.map(a => ({ r: a[0], c: a[1], len: a[2], dir: a[3] }));
  const key = levelKey(pieces, lv.w || []);
  if(!seen.has(key)) seen.set(key, { m: lv.m, d: lv.d, p: lv.p, w: lv.w?.length ? lv.w : undefined, key });
});
// Exclude anything already claimed by Bounty or Impound — score-fogleman-
// reserve.mjs checked the Fogleman reserve against both, but the bridge
// and native pools (freshly generated here) never have been; a board
// showing up in two contexts would be a real curation bug (see
// verify-levels.mjs's cross-pool dedupe check).
const bountyMod = await import(join(ROOT, 'js', 'bounty-rotation.data.js'));
const impoundMod = await import(join(ROOT, 'js', 'impound-lot.data.js'));
const claimedElsewhere = new Set();
[...bountyMod.BOUNTY_ROTATION, ...impoundMod.IMPOUND_LOT].forEach(lv => {
  const pieces = lv.p.map(a => ({ r: a[0], c: a[1], len: a[2], dir: a[3] }));
  claimedElsewhere.add(levelKey(pieces, lv.w || []));
});
const pool = [...seen.values()].filter(lv => !claimedElsewhere.has(lv.key));
console.log(`Combined unique pool: ${pool.length} candidates (need ${TOTAL}).`);
if(pool.length < TOTAL) throw new Error(`Only ${pool.length} candidates, need ${TOTAL}.`);

// Every one of the 200 pre-expansion levels must survive into the new
// 500 — "reorder ALL existing levels", not "curate 500 from a combined
// pool that might drop a few" — so mark them now, before any sampling
// step gets a chance to skip one. (A representative/stride sample over
// the WHOLE pool, tried first, silently dropped 3 of the 200 in favor of
// new supply nearby in score — fine numerically, but not what was asked.)
const existingKeySet = new Set(legacyKeys);

// 3. Intro ramp: easiest-by-score boards at the exact scripted pars.
pool.sort((a, b) => a.d - b.d);
const used = new Set();
const intro = INTRO_PARS.map(par => {
  const cand = pool.find(lv => !used.has(lv.key) && lv.m === par && !(lv.w && lv.w.length));
  if(!cand) throw new Error(`No intro board with par ${par} available.`);
  used.add(cand.key);
  return cand;
});

// 4. Sort the remainder by score. Supply is a ~2.4x surplus (1175
// available for 497 needed) but very unevenly dense — mostly clustered
// at the easy end plus a big Fogleman pile around d41-56 — so taking a
// straight prefix (rest.slice(0, 497)) would only use the bottom slice
// of the WHOLE range and never reach the hardest boards at all. Instead,
// stride-sample a representative subset spread evenly across the FULL
// sorted range first, THEN chunk that (already-sorted, so still
// monotonic) subset into 10 contiguous chapters. The 200 pre-expansion
// boards are exempt from that sampling — guaranteed a slot outright —
// so only the ADDITIONAL new-supply candidates compete for the
// remaining seats.
const restAll = pool.filter(lv => !used.has(lv.key)).sort((a, b) => a.d - b.d);
const restGuaranteed = restAll.filter(lv => existingKeySet.has(lv.key));
const restOptional = restAll.filter(lv => !existingKeySet.has(lv.key));
const neededRest = TOTAL - intro.length;
const neededOptional = neededRest - restGuaranteed.length;
if(neededOptional < 0) throw new Error(`Guaranteed existing levels (${restGuaranteed.length}) alone exceed the ${neededRest} remaining slots.`);
if(restOptional.length < neededOptional) throw new Error(`Only ${restOptional.length} optional boards left, need ${neededOptional}.`);

// Segment-midpoint sampling (over restOptional only — restGuaranteed's
// pre-expansion boards are never subject to this, they're all already
// counted in), not stride-from-start: picking the MIDPOINT of each
// board's own dedicated (restOptional.length/neededOptional)-wide
// segment guarantees strictly increasing indices with no possible
// collisions (two segments can't floor to the same index — consecutive
// midpoints are always >= 1 apart since neededOptional <= restOptional
// .length by the check above). An earlier stride-from-start version
// could pin multiple trailing picks to the same boundary index once
// rounding ran out of room, silently duplicating a board into the
// campaign more than once — caught by verify-levels.mjs's duplicate-key
// check.
const segment = neededOptional > 0 ? restOptional.length / neededOptional : 0;
const sampledOptional = [];
for(let i = 0; i < neededOptional; i++){
  const idx = Math.min(restOptional.length - 1, Math.floor((i + 0.5) * segment));
  sampledOptional.push(restOptional[idx]);
}
const representative = [...restGuaranteed, ...sampledOptional].sort((a, b) => a.d - b.d);

const chapters = [];
for(let ci = 0; ci < NUM_CHAPTERS; ci++){
  const from = ci === 0 ? 0 : ci * PER_CHAPTER - intro.length;
  const count = ci === 0 ? PER_CHAPTER - intro.length : PER_CHAPTER;
  const slice = representative.slice(from, from + count);
  chapters.push(ci === 0 ? [...intro, ...slice] : slice);
}
const chosen = chapters.flat();
if(chosen.length !== TOTAL) throw new Error(`Selected ${chosen.length}, expected ${TOTAL}.`);

// 5. Re-verify every single level against our own solver before shipping
// anything — every source already claims a verified m/d, but a fresh
// end-to-end check is cheap insurance against a transcription bug in the
// combine step above (wrong walls carried over, etc).
console.log('Re-verifying all 500 levels…');
const t0 = Date.now();
chosen.forEach((lv, i) => {
  const pieces = lv.p.map(a => ({ r: a[0], c: a[1], len: a[2], dir: a[3] }));
  const hitches = lv.h;
  const sol = solve(pieces, { walls: lv.w, hitches, maxStates: 2000000 });
  if(!sol.solvable || sol.optimal !== lv.m){
    throw new Error(`Level ${i + 1} (key ${lv.key}) failed verification: claimed par ${lv.m}, solver says ${sol.solvable ? sol.optimal : 'unsolvable'}`);
  }
  if(i >= intro.length && lv.m < chosen[intro.length].m){
    // sanity check only — actual floor enforced by chapter 1's own content
  }
});
console.log(`All 500 verified in ${((Date.now() - t0) / 1000).toFixed(1)}s.`);

// Monotonic non-decreasing score sanity check across chapter boundaries.
for(let ci = 1; ci < NUM_CHAPTERS; ci++){
  const prevMax = Math.max(...chapters[ci - 1].map(l => l.d));
  const curMin = Math.min(...chapters[ci].map(l => l.d));
  if(curMin < prevMax - 0.01){
    console.warn(`  note: chapter ${ci} min score (${curMin.toFixed(1)}) is below chapter ${ci - 1} max (${prevMax.toFixed(1)}) — should be impossible given a global sort, investigate.`);
  }
}

console.log('\nChapter summary:');
chapters.forEach((ch, i) => {
  const ms = ch.map(l => l.m), ds = ch.map(l => l.d);
  console.log(`  Ch${i + 1} ${CHAPTER_META[i].name}: par ${Math.min(...ms)}-${Math.max(...ms)}, score ${Math.min(...ds).toFixed(1)}-${Math.max(...ds).toFixed(1)}`);
});

if(DRY_RUN){
  console.log('\n--dry-run: not writing js/levels.data.js.');
  process.exit(0);
}

const levelsJs = `/* AUTO-GENERATED by tools/extend-to-500.mjs (built on top of
   tools/generate-levels.mjs + tools/add-hitch-levels.mjs +
   tools/add-fogleman-levels.mjs's original 200) — do not edit by hand.
   500 levels, verified optimal (m = par), curved by difficulty model v1
   score (d), 10 chapters of 50. See docs/LEVELS-500-PLAN.md. Neon
   District (chapter 2) carries hitch puzzles — pieces marked in a
   level's \`h\` array need towing/decoupling to clear, per
   js/solver.js's hitch rules. */

export const CHAPTER_SIZE = ${PER_CHAPTER};

/* Levels 1-INTRO ease in below chapter 1's floor; every later level needs >= chapter 1's floor. */
export const INTRO = ${INTRO_PARS.length};

export const CHAPTERS = ${JSON.stringify(
    CHAPTER_META.map((meta, i) => {
      const ms = chapters[i].map(l => l.m);
      return { name: meta.name, accent: meta.accent, from: i * PER_CHAPTER, minM: Math.min(...ms), maxM: Math.max(...ms), heistSlack: meta.heistSlack, pursuitThink: meta.pursuitThink };
    }), null, 2)};

export const LEVELS = [
${chosen.map(lv => JSON.stringify({ m: lv.m, d: lv.d, p: lv.p, ...(lv.w?.length ? { w: lv.w } : {}), ...(lv.h ? { h: lv.h } : {}) })).join(',\n')}
];
`;
writeFileSync(LEVELS_PATH, levelsJs);
console.log(`\nWrote ${LEVELS_PATH} (500 levels, 10 chapters).`);
