#!/usr/bin/env node
/* Measures every car photo's actual painted geometry and writes
   js/car-art.data.js, which js/art.js uses to anchor the hero
   headlight/taillight glows to each car's real nose and tail instead of
   one hardcoded position.

   Why this exists: the beam/lamp overlay in vehicleSVG was hand-tuned to
   classic.webp and applied verbatim to every other photo. That was fine
   while classic.webp was the only hero render, but the shipped art is not
   consistently normalized — measured nose positions run from 87.9% to
   98.5% of canvas width, against a documented spec of "car fills 97% of
   the canvas length". So the glows sat on the lamps for classic.webp and
   drifted onto the bonnet, or off the body entirely, for everything else.

   This measures rather than guesses. It deliberately does NOT try to
   locate the baked headlights themselves: two attempts at that (absolute
   brightness, then a per-car brightness percentile) both failed on
   white/cream bodies, where the panels are as bright as the lamps. The
   alpha bounding box is unambiguous for every asset, and anchoring to the
   car's front corners keeps the glow on the vehicle — which is the actual
   visible defect — even where it isn't pixel-perfect on the lamp itself.

   Run: node tools/measure-car-art.mjs   (needs sharp, already a devDep
   via @capacitor/assets — same dependency tools/build-icons.mjs uses)

   Re-run whenever car art is added or replaced; the data file is checked
   in so neither the game nor tools/verify-levels.mjs needs sharp at
   runtime. */

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const CARS_DIR = 'assets/cars';
const OUT = 'js/car-art.data.js';

// Vehicles only — trailers/trucks never render as a hero.
const files = fs.readdirSync(CARS_DIR)
  .filter(f => f.endsWith('.webp'))
  .sort();

const ALPHA = 40;    // opaque enough to count as painted car
const END = 0.12;    // sample the outer 12% of the car for nose/tail spans

async function measure(file){
  const { data, info } = await sharp(path.join(CARS_DIR, file))
    .ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width: W, height: H, channels: C } = info;
  const a = (px, py) => data[(py * W + px) * C + 3];

  let minX = Infinity, maxX = -1, minY = Infinity, maxY = -1;
  for(let py = 0; py < H; py++) for(let px = 0; px < W; px++){
    if(a(px, py) > ALPHA){
      if(px < minX) minX = px; if(px > maxX) maxX = px;
      if(py < minY) minY = py; if(py > maxY) maxY = py;
    }
  }
  if(maxX < 0) return null;   // fully transparent — nothing to anchor to
  const carW = maxX - minX;

  // Vertical span within a slice at each end of the car. The front slice
  // is what the headlights straddle; the rear slice the taillights.
  const spanIn = (fromX, toX) => {
    let lo = Infinity, hi = -1;
    for(let py = 0; py < H; py++) for(let px = fromX; px <= toX; px++){
      if(a(px, py) > ALPHA){ if(py < lo) lo = py; if(py > hi) hi = py; }
    }
    return [lo, hi];
  };
  const [fLo, fHi] = spanIn(Math.floor(maxX - carW * END), maxX);
  const [rLo, rHi] = spanIn(minX, Math.ceil(minX + carW * END));

  const pctW = v => +(v / W * 100).toFixed(1);
  const pctH = v => +(v / H * 100).toFixed(1);
  return {
    nose: pctW(maxX), tail: pctW(minX),
    fTop: pctH(fLo), fBot: pctH(fHi),
    rTop: pctH(rLo), rBot: pctH(rHi),
  };
}

const out = {};
for(const f of files){
  const m = await measure(f);
  if(m) out[`${CARS_DIR}/${f}`] = m;
}

const body = Object.entries(out)
  .map(([k, v]) => `  '${k}': { nose: ${v.nose}, tail: ${v.tail}, fTop: ${v.fTop}, fBot: ${v.fBot}, rTop: ${v.rTop}, rBot: ${v.rBot} },`)
  .join('\n');

fs.writeFileSync(OUT, `/* GENERATED by tools/measure-car-art.mjs — do not hand-edit.
   Re-run that tool after adding or replacing any car art.

   Each entry is one photo's painted extent, as percentages of its own
   canvas: \`nose\`/\`tail\` are the front (right) and rear (left) edges of
   the opaque pixels, and \`fTop\`/\`fBot\` (\`rTop\`/\`rBot\`) are the vertical
   span of the car within the outer 12% at that end — i.e. how wide the
   car actually is where its headlights (taillights) sit.

   js/art.js anchors the hero light overlay to these instead of to one set
   of constants tuned to classic.webp. See that file's photoHeroExtra. */
export const CAR_ART_GEOMETRY = {
${body}
};
`);

console.log(`measured ${Object.keys(out).length} car photos -> ${OUT}`);
const noses = Object.values(out).map(v => v.nose);
console.log(`nose position spread: ${Math.min(...noses)}% .. ${Math.max(...noses)}% of canvas width`);
